version: "3.8"

services:

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${SECRET_KEY}
    volumes:
      - minio-data:/data
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  clamav:
      build: 
          context: .
          dockerfile: clamav_updates.dockerfile
      image: clamav
      ports:
        - "3310:3310" 

volumes:
  minio-data:
  clamav-data:

networks:
  app-network:
